import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { ChatResponse } from './models/chat-response.model';
import { Message } from './models/message.model';
import { ConversationStarter } from './models/conversation-starter.model';
import { OpenAI } from 'openai';

/*
 * To set up your API key, create a file named 'environment.ts' in the 'src/environments' folder.
 * The file should have the following content:
 *
 * export const environment = {
 *   production: false,
 *   apiKey: 'YOUR_API_KEY_HERE',
 * };
 *
 * Replace 'YOUR_API_KEY_HERE' with your actual OpenAI API key.
 */

@Injectable({
  providedIn: 'root'
})
export class ChatGptService {

  /**
   *
   */
  constructor(private http: HttpClient) {
  }

  /**
   * Self-Registration
   * @param email E-Mail of user, e.g. "michael.wechner@wyona.com"
   * @param language Language of user, e.g. "de" or "en"
   */
  async selfRegister(email: string, firstname: string, lastname: string, language: string): Promise<any> {
    console.info("Self-registration '" + email + "' ...");

    var linkedInUrl = "";
    var howDidYouLearnAboutKatie = "";
    var usage = "";
    var expectations = "";

    var requestUrl = "./api/v1/self-register?h-captcha-response-token=" + "TODO";

    let promise = new Promise<void>((resolve, reject) => {
      this.http.post(requestUrl, { email: email, firstName: firstname, lastName: lastname, language: language, linkedInUrl: linkedInUrl, howDidYouLearnAboutKatie: howDidYouLearnAboutKatie, howDoYouWantToUseKatie: usage, whatAreYourExpectations: expectations }, { responseType: 'json' })
        .toPromise()
        .then(response => {
          //alert("DEBUG: Self-registration successful");
          console.info("Self-registration successful");
          resolve();
          })
        .catch(response => {
          console.error("Response status: " + response.status);
          var error = <Error>response.error; // INFO: This works, because we use httpClient instead http
          console.info("An error occured when trying to self-register user: " + error.message);
          reject(error.message);
        });
    });

    //alert("DEBUG: Trying to self-register ...");
    console.info("Trying to self-register ...");
    return promise;
  }

  /**
   *
   */
  async getConversationStarters(): Promise<any> {
    console.info("Get conversation starters ...");

    type Headers = {[key: string] : any};
    const headers: Headers = {};
    headers['Content-Type'] = 'application/json';
/* INFO: We use session instead API key
    if (environment.apiKey != null) {
      headers['Authorization'] = 'Bearer ' + environment.apiKey;
    } else {
      console.warn("No API key configured.");
    }
*/

    var requestUrl = "./api/v1/learning-coach/conversation-starters";

    console.info("ChatGptService#getConversationStarters(): Get conversation starters '" + requestUrl + "' ...");
    let promise = new Promise((resolve, reject) => {
      this.http.get(requestUrl, { headers })
        .toPromise()
        .then(response => {
          var starters = <ConversationStarter[]>response;
          console.info("ChatGptService#getConversationStarters(): Number of conversation starters: " + starters.length);
          resolve(starters);
        })
        .catch(response => {
          console.error("ChatGptService#getConversationStarters(): Response status: " + response.status);
          resolve([]);
        });
    });
    return promise;
  }

  /**
   * Chat with LLM
   * @param conversation_id Conversation Id (generated by remote LLM server)
   * @param messages Previous chat messages
   * @param chosenSuggestion Optional conversation starter
   * @return chat response of LLM
   */
  chat(conversation_id: string | null, messages: Array<Message>, chosenSuggestion: {type: string; index: string} | null): Observable<ChatResponse> {

    type Body = {[key: string] : any};
    const body: Body = {};
    if (conversation_id != null) {
      body['conversation_id'] = conversation_id;
    }
    body['model'] = environment.model;
    body['messages'] = this.replaceRoleError(messages);
    body['temperature'] = environment.temperature;
    body['stream'] = false;
    if (chosenSuggestion != null) {
      body['chosen_suggestion'] = chosenSuggestion;
    }
/*
    const body = {
      model: 'gpt-4o',
      messages: messages,
      temperature: 0.5, // adjust the temperature of the response - 0.5 works well with programming questions
    };
*/

    type Headers = {[key: string] : any};
    const headers: Headers = {};
    headers['Content-Type'] = 'application/json';
/* INFO: We use session instead API key
    if (environment.apiKey != null) {
      headers['Authorization'] = 'Bearer ' + environment.apiKey;
    } else {
      console.warn("No API key configured.");
    }
*/
/*
    const headers = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${environment.apiKey}` // see note on top
    };
*/

    console.info("ChatGptService#chat(): Send request to '" + environment.apiUrl + "' ...");

    // Consider returning HttpResponse instead directly OpenAI chat response
    return this.http.post<ChatResponse>(environment.apiUrl, body, { headers });
  }

  /**
   * Replace role "error" by "assistant", because most LLMs do not support role "error"
   */
  replaceRoleError(messages: Array<Message>): Array<Message> {
    let messagesToLLM: Array<Message> = [];
    console.info("ChatGptService#replaceRoleError(): Replace role 'error' by 'assistant' ...");
    for (var msg of messages) {
      console.info("Role: " + msg.role);
      var role = msg.role;
      if (msg.role == "error") {
        role = "assistant";
      }
      messagesToLLM.push({ role : role, content: msg.content });
    }
    return messagesToLLM;
  }
}
